Qwill/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

Qwill/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

Qwill/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Qwill/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }

        public IActionResult OnPostNewWill()
        {
            //return RedirectToPage("/Steps/Prerequisites/WhereLive");

            //return RedirectToPage("/Steps/Register");

            return RedirectToPage("/Steps/Customer");
        }
    }
}

Qwill/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Qwill/Pages/Step2.cshtml.cs
using ApplicationCore.Entities;
using ApplicationCore.Helpers;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Qwill.Interfaces;
using Qwill.ViewModels;
using System;
using System.Linq;

namespace Qwill.Pages
{
    public class Step2Model : PageModel
    {
        //private readonly IWillVmService _willVmService;
        //private readonly IAppLogger<Step2Model> _logger;

        //private readonly string _errorNotFound;
        //private readonly string _errorDefaultMessage;

        //public Step2Model(IWillVmService willVmService, IAppLogger<EditModel> appLogger)
        //{
        //    _willVmService = willVmService;
        //    _logger = appLogger;

        //    _errorNotFound = "Your will could not be found.";
        //    _errorDefaultMessage = "It appears something went wrong. Please try again later. Should you still have the same issue, please get in touch with support.";
        //}

        //[BindProperty]
        //public WillVm WillInfo { get; set; } = new WillVm();

        //[TempData]
        //public string ErrorMessage { get; set; }

        //public void OnGet(Guid id)
        //{
        //    try
        //    {
        //        WillInfo = _willVmService.Get(id);

        //        //Sample data
        //        WillInfo.Children.Add(new Child() { Id = Guid.NewGuid(), FirstName = "Adam", Over18 = false });
        //        WillInfo.Children.Add(new Child() { Id = Guid.NewGuid(), FirstName = "Brian", Over18 = true });
        //        WillInfo.Children.Add(new Child() { Id = Guid.NewGuid(), FirstName = "Chris", Over18 = true });
        //    }
        //    catch (ArgumentNullException e)
        //    {
        //        _logger.LogWarning("Step2 OnGet exception", e.Message);
        //        ErrorMessage = _errorNotFound;
        //    }
        //    catch (Exception e)
        //    {
        //        _logger.LogWarning("Step2 OnGet exception", e.Message);
        //        ErrorMessage = _errorDefaultMessage;
        //    }
        //}

        //public IActionResult OnPost()
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return Page();
        //    }

        //    var willId = _willVmService.Post(WillInfo);

        //    //Success
        //    if (willId != null) return RedirectToPage("/Step3/" + willId.Value);

        //    //Error
        //    _logger.LogWarning("Step2 OnPost exception", _errorDefaultMessage);
        //    return Page();
        //}

        //public IActionResult OnPostSaveChildDetails([FromBody]ChildVm childData)
        //{
        //    WillInfo = _willVmService.Get(childData.WillId);

        //    if (childData.ChildId.Value.IsGuid())
        //    {
        //        var child = WillInfo.Children.FirstOrDefault(c => c.Id == childData.ChildId);
        //        WillInfo.Children.Remove(child);
        //    }

        //    WillInfo.Children.Add(new Child() { FirstName = childData.ChildName, Over18 = childData.Over18 });

        //    return new JsonResult("true");
        //}
    }
}

Qwill/Pages/StepSignature.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages
{
    public class StepSignatureModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Qwill/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

Qwill/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Qwill/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<p></p>

<form method="post" asp-page-handler="NewWill">
    <div class="row">
        <div class="col-md-3">
            <button class="btn btn-primary" type="submit">New Will</button>
        </div>
        <div class="col-md-3">
            <a asp-page="/Will/Edit" asp-route-id="1">Edit</a>
        </div>
    </div>
</form>

Qwill/Pages/Step2.cshtml
@page
@using Newtonsoft.Json
@model Qwill.Pages.Step2Model
@{
    ViewData["Title"] = "Step2";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<!-- todo: This should be in JSON format -->
@*<input type="hidden" name="data" asp-for="WillInfo.Children" />*@

<h2>Step2</h2>

@*<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <div>
                <partial name="_ErrorMessages" for="ErrorMessage" />

                <form method="post" asp-page-handler="Step2Form">
                    <input type="hidden" asp-for="WillInfo.Id" />

                    <div class="mb-3">
                        <h3>Do you have any children under 18?</h3>
                    </div>

                    <div class="mb-3">
                        <a class="btn btn-primary btn-block" data-toggle="modal" data-target="#childModal">Add Child</a>
                    </div>

                    <div childListTarget class="mb-5">
                    </div>

                    <button class="btn btn-primary btn-block" type="submit">Next</button>
                </form>
            </div>
        </div>
    </div>
</div>*@


<!-- Child Modal -->
@*<div id="childModal" class="modal fade responsiveModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">

                <input type="hidden" id="childId" />

                <div class="mb-3">
                    <label>First Name</label>
                    <input FirstName class="form-control" placeholder="Name *" />
                    <span FirstNameValidation class="text-danger"></span>
                </div>

                <div class="mb-5">
                    <label>
                        Over 18?
                        <input Over18 type="checkbox" />
                    </label>
                    <span Over18Validation class="text-danger"></span>
                </div>

                <button save-child-button class="btn btn-primary btn-block" type="submit">Save</button>
            </div>
        </div>
    </div>
</div>*@


@section Scripts {

    @*<script type="text/javascript">
        var json = @Html.Raw(JsonConvert.SerializeObject(Model.WillInfo.Children, new JsonSerializerSettings
                   {
                        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                   }));
    </script>


    <script src="~/js/step2.js"></script>*@
}

Qwill/Pages/StepSignature.cshtml
@page
@model Qwill.Pages.StepSignatureModel
@{
    ViewData["Title"] = "StepSignature";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Step Signature</h2>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <div>
                <canvas id="testatorSketch" class="canvas"></canvas>
            </div>
        </div>
    </div>
</div>



@section scripts
{
    <script src="~/js/sketch.js"></script>
}