Qwill/Pages/Steps/ChildrenExisting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages.Steps
{
    public class ChildrenExistingModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Qwill/Pages/Steps/Customer.cshtml.cs
using ApplicationCore.Interfaces;
using Infrastructure.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Qwill.Interfaces;
using Qwill.ViewModels;
using System;
using System.Threading.Tasks;

namespace Qwill.Pages.Steps
{
    public class CustomerModel : PageModel
    {
        private readonly IWillVmService _willVmService;
        private readonly ICustomerVmService _customerVmService;
        private readonly IMaritalStatusVmService _maritalStatusService;
        private readonly IAppLogger<CustomerModel> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly string _errorNotFound;
        private readonly string _errorDefaultMessage;

        public CustomerModel(IWillVmService willVmService, ICustomerVmService customerVmService,
                             IMaritalStatusVmService maritalStatusService,
                             IAppLogger<CustomerModel> appLogger, SignInManager<ApplicationUser> signInManager,
                             UserManager<ApplicationUser> userManager)
        {
            _willVmService = willVmService;
            _customerVmService = customerVmService;
            _maritalStatusService = maritalStatusService;
            _logger = appLogger;
            _signInManager = signInManager;
            _userManager = userManager;

            _errorNotFound = "Your will could not be found.";
            _errorDefaultMessage = "It appears something went wrong. Please try again later. Should you still have the same issue, please get in touch with support.";
        }

        [BindProperty]
        public MaritalStatusVm MaritalStatusInfo { get; set; }
        [BindProperty]
        public WillVm WillInfo { get; set; } = new WillVm();
        [BindProperty]
        public CustomerVm CustomerInfo { get; set; } = new CustomerVm();

        [TempData]
        public string ErrorMessage { get; set; }

        public async Task OnGet(Guid id)
        {
            MaritalStatusInfo = _maritalStatusService.GetAll();

            GetWillInfo(id);

            await GetCustomerInfo();

            //var user = _userManager.FindByNameAsync(userName);

            //if (_signInManager.IsSignedIn(HttpContext.User))
            //{
            //    var x = 1;
            //}
            //else
            //{
            //    var y = 2;
            //}
        }

        private void GetWillInfo(Guid id)
        {
            try
            {
                WillInfo = _willVmService.Get(id);
            }
            catch (ArgumentNullException e)
            {
                _logger.LogWarning("Customer GetWillInfo exception", e.Message);
                ErrorMessage = _errorNotFound;
            }
            catch (Exception e)
            {
                _logger.LogWarning("Customer GetWillInfo exception", e.Message);
                ErrorMessage = _errorDefaultMessage;
            }

            // Populate
            if (!string.IsNullOrEmpty(WillInfo.UserName))
            {
                WillInfo.UserName = HttpContext.User.Identity.Name;
            }
            else
            {
                WillInfo.UserName = "aa@aa.com";
            }
        }

        private async Task GetCustomerInfo()
        {
            try
            {
                CustomerInfo = await _customerVmService.GetByWillId(WillInfo.Id);
            }
            catch (ArgumentNullException e)
            {
                _logger.LogWarning("Customer GetCustomerInfo exception", e.Message);
                ErrorMessage = _errorNotFound;
            }
            catch (Exception e)
            {
                _logger.LogWarning("Customer GetCustomerInfo exception", e.Message);
                ErrorMessage = _errorDefaultMessage;
            }
        }


        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                MaritalStatusInfo = _maritalStatusService.GetAll();
                return Page();
            }

            var willId = _willVmService.Post(WillInfo);
            CustomerInfo.WillId = willId ?? Guid.Empty;
            var customerId = _customerVmService.Post(CustomerInfo);

            //Error
            if (willId == null || customerId == null)
            {
                _logger.LogWarning("Customer OnPost exception", _errorDefaultMessage);

                MaritalStatusInfo = _maritalStatusService.GetAll();
                return Page();
            }

            return RedirectToPage(GetNextStep(), new { id = willId.Value });
        }

        private string GetNextStep()
        {
            var maritalStatus = _maritalStatusService.Get(CustomerInfo.MaritalStatusId);

            return (maritalStatus.Description == "Married" || maritalStatus.Description == "Civil Partnership")
                ? "/Steps/Partner"
                : "/Steps/ChildrenExisting";
        }
    }
}

Qwill/Pages/Steps/Partner.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Qwill.Interfaces;
using Qwill.ViewModels;

namespace Qwill.Pages.Steps
{
    public class PartnerModel : PageModel
    {
        private readonly IWillVmService _willVmService;
        private readonly IAppLogger<PartnerModel> _logger;

        private readonly string _errorNotFound;
        private readonly string _errorDefaultMessage;

        public PartnerModel(IWillVmService willVmService, IAppLogger<PartnerModel> appLogger)
        {
            _willVmService = willVmService;
            _logger = appLogger;

            _errorNotFound = "Your will could not be found.";
            _errorDefaultMessage = "It appears something went wrong. Please try again later. Should you still have the same issue, please get in touch with support.";
        }

        [BindProperty]
        public WillVm WillInfo { get; set; } = new WillVm();
        [BindProperty]
        public PartnerVm PartnerInfo { get; set; } = new PartnerVm();

        [TempData]
        public string ErrorMessage { get; set; }

        public void OnGet(Guid id)
        {
            GetWillInfo(id);

            //await GetCustomerInfo();
        }

        private void GetWillInfo(Guid id)
        {
            try
            {
                WillInfo = _willVmService.Get(id);
            }
            catch (ArgumentNullException e)
            {
                _logger.LogWarning("Partner GetWillInfo exception", e.Message);
                ErrorMessage = _errorNotFound;
            }
            catch (Exception e)
            {
                _logger.LogWarning("Partner GetWillInfo exception", e.Message);
                ErrorMessage = _errorDefaultMessage;
            }
        }

    }
}

Qwill/Pages/Steps/Prerequisites/ChildrenPrevious.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages.Steps.Prerequisites
{
    public class ChildrenPreviousModel : PageModel
    {
        public IActionResult OnGet()
        {
            var referer = Request.Headers["Referer"].ToString();

            if (!IsValidReferer(referer))
                return RedirectToPage("/Steps/Prerequisites/NotPossible");

            return Page();
        }

        public bool IsValidReferer(string referer)
        {
            return referer.Contains("/Steps/Prerequisites/Following");
        }

        public IActionResult OnPostYes()
        {
            return RedirectToPage("/Steps/Prerequisites/NotPossible");
        }

        public IActionResult OnPostNo()
        {
            return RedirectToPage("/Steps/Register");
        }

        public IActionResult OnPostGoBack()
        {
            return RedirectToPage("/Steps/Prerequisites/Following");
        }
    }
}

Qwill/Pages/Steps/Prerequisites/Following.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages.Steps.Prerequisites
{
    public class FollowingModel : PageModel
    {
        public IActionResult OnGet()
        {
            var referer = Request.Headers["Referer"].ToString();

            if (!IsValidReferer(referer))
                return RedirectToPage("/Steps/Prerequisites/NotPossible");

            return Page();
        }

        public bool IsValidReferer(string referer)
        {
            return referer.Contains("/Steps/Prerequisites/WhereLive") || referer.Contains("/Steps/Prerequisites/ChildrenPrevious");
        }

        public IActionResult OnPostYes()
        {
            return RedirectToPage("/Steps/Prerequisites/NotPossible");
        }

        public IActionResult OnPostNo()
        {
            return RedirectToPage("/Steps/Prerequisites/ChildrenPrevious");
        }

        public IActionResult OnPostGoBack()
        {
            return RedirectToPage("/Steps/Prerequisites/WhereLive");
        }
    }
}

Qwill/Pages/Steps/Prerequisites/NotPossible.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Qwill.Pages.Steps.Prerequisites
{
    public class NotPossibleModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Qwill/Pages/Steps/Prerequisites/WhereLive.cshtml.cs
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Qwill.Interfaces;
using Qwill.ViewModels;
using System;

namespace Qwill.Pages.Steps.Prerequisites
{
    public class WhereLiveModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostAcceptable()
        {
            return RedirectToPage("/Steps/Prerequisites/Following");
        }

        public IActionResult OnPostElsewhere()
        {
            return RedirectToPage("/Steps/Prerequisites/NotPossible");
        }
    }
}

Qwill/Pages/Steps/Register.cshtml.cs
using Infrastructure.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Qwill.ViewModels;
using System.Threading.Tasks;

namespace Qwill.Pages.Steps
{
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RegisterModel(SignInManager<ApplicationUser> signInManager,
                             UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [BindProperty]
        public RegisterVm UserDetails { get; set; }

        public async Task<IActionResult> OnPostCreateAccount()
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = UserDetails.Email, Email = UserDetails.Email };
                var result = await _userManager.CreateAsync(user, UserDetails.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return LocalRedirect("/Steps/Customer");
                }
                AddErrors(result);
            }
            return Page();
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }

    }
}

Qwill/Pages/Steps/ChildrenExisting.cshtml
@page
@model Qwill.Pages.Steps.ChildrenExistingModel
@{
    ViewData["Title"] = "ChildrenExisting";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">

        <div class="col-6 offset-3">
            <h5>Do you have any children from a current relationship?</h5>

            <div class="mt-3">
                <form method="post">
                    <button class="btn btn-primary btn-block" asp-page-handler="Yes">Yes</button>
                    <button class="btn btn-primary btn-block" asp-page-handler="No">No</button>
                    <button class="btn btn-link" asp-page-handler="GoBack">Go Back</button>
                </form>
            </div>
        </div>

    </div>
</div>

Qwill/Pages/Steps/Customer.cshtml
@page
@model Qwill.Pages.Steps.CustomerModel
@{
    ViewData["Title"] = "Customer";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Customer</h2>

<div class="container">
    <div class="row">

        <div class="col-6 offset-3">
            <h5>Your details</h5>

            <div class="mt-3">
                <partial name="_ErrorMessages" for="ErrorMessage" />

                <form method="post">
                    <input type="hidden" asp-for="WillInfo.Id" />
                    <input type="hidden" asp-for="WillInfo.WillStatus" />
                    <input type="hidden" asp-for="WillInfo.UserName" />

                    <div class="mb-3">
                        <label asp-for="CustomerInfo.FirstName"></label>
                        <input asp-for="CustomerInfo.FirstName" class="form-control" placeholder="Name *" />
                        <span asp-validation-for="CustomerInfo.FirstName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="CustomerInfo.LastName"></label>
                        <input asp-for="CustomerInfo.LastName" class="form-control" placeholder="Name *" />
                        <span asp-validation-for="CustomerInfo.LastName" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <partial name="_Date" for="CustomerInfo.DateOfBirth" />
                    </div>

                    <div class="mb-3">
                        <partial name="_MaritalStatus" for="MaritalStatusInfo" />
                        <input type="hidden" asp-for="CustomerInfo.MaritalStatusId" id="id_customermaritalstatus" />
                    </div>

                    <div class="mb-3">
                        <partial name="_Address" for="CustomerInfo.Address" />
                    </div>

                    <div class="mb-3">
                        <label asp-for="CustomerInfo.Telephone"></label>
                        <input asp-for="CustomerInfo.Telephone" class="form-control" placeholder="Name *" />
                        <span asp-validation-for="CustomerInfo.Telephone" class="text-danger"></span>
                    </div>

                    <button class="btn btn-primary btn-block" type="submit">Next</button>
                    <button class="btn btn-link" asp-page-handler="GoBack">Go Back</button>
                </form>
            </div>
        </div>

    </div>
</div>


@section Scripts {
    <script src="~/js/PAF.js"></script>
    <script src="~/js/maritalstatus.js"></script>
    <script src="~/js/customer.js"></script>
} 

Qwill/Pages/Steps/NotPossible.cshtml
@page
@model Qwill.Pages.Steps.NotPossibleModel
@{
    ViewData["Title"] = "NotPossible";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Not Possible</h2>

<div class="container">
    <div class="row">

        <div class="col-6 offset-3">
            <div>Unfortunately, we cannot process your will.</div>
        </div>

    </div>
</div>

Qwill/Pages/Steps/Partner.cshtml
@page
@model Qwill.Pages.Steps.PartnerModel
@{
    ViewData["Title"] = "Partner";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Partner</h2>

<div class="container">
    <div class="row">

        <div class="col-6 offset-3">
            <h5>Your details</h5>

            <div class="mt-3">
                <partial name="_ErrorMessages" for="ErrorMessage" />

                <form method="post">
                    <input type="hidden" asp-for="WillInfo.Id" />
                    <input type="hidden" asp-for="WillInfo.WillStatus" />
                    <input type="hidden" asp-for="WillInfo.UserName" />

                    <div class="mb-3">
                        <label asp-for="PartnerInfo.FirstName"></label>
                        <input asp-for="PartnerInfo.FirstName" class="form-control" placeholder="Name *" />
                        <span asp-validation-for="PartnerInfo.FirstName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="PartnerInfo.LastName"></label>
                        <input asp-for="PartnerInfo.LastName" class="form-control" placeholder="Name *" />
                        <span asp-validation-for="PartnerInfo.LastName" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <partial name="_Date" for="PartnerInfo.DateOfBirth" />
                    </div>

                    <div class="mb-3">
                        <partial name="_Address" for="PartnerInfo.Address" />
                    </div>

                    <button class="btn btn-primary btn-block" type="submit">Next</button>
                    <button class="btn btn-link" asp-page-handler="GoBack">Go Back</button>
                </form>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    <script src="~/js/PAF.js"></script>
    <script src="~/js/partner.js"></script>
}

Qwill/Pages/Steps/Register.cshtml
@page
@model Qwill.Pages.Steps.RegisterModel
@{
    ViewData["Title"] = "Register";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">

        <div class="col-6 offset-3">
            <h5>Sign up to continue</h5>

            <div class="mt-3">
                <form method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="UserDetails.Email" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="UserDetails.Email" class="form-control" />
                            <span asp-validation-for="UserDetails.Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserDetails.Password" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="UserDetails.Password" class="form-control" />
                            <span asp-validation-for="UserDetails.Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserDetails.ConfirmPassword" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="UserDetails.ConfirmPassword" class="form-control" />
                            <span asp-validation-for="UserDetails.ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>

                    <button class="btn btn-primary btn-block" asp-page-handler="CreateAccount">Create Account</button>
                    <button class="btn btn-link" asp-page-handler="SignIn">Already have an account? Sign In</button>
                    <button class="btn btn-link" asp-page-handler="GoBack">Go Back</button>
                </form>
            </div>
        </div>

    </div>
</div>